version: '{build}'

image: Visual Studio 2019 Preview

pull_requests:
  # Do not increment build number for pull requests
  do_not_increment_build_number: true

nuget:
  # Do not publish NuGet packages for pull requests
  disable_publish_on_pr: true

environment:
  # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

configuration: Release

branches:
  only:
    - master

before_build:
- dotnet restore

build_script:
- dotnet publish --version-suffix "$env:appveyor_build_number"

artifacts:
# Store NuGet packages
- path: .\Artifacts\**\*.nupkg
  name: NuGet

deploy:
# Publish NuGet packages
- provider: NuGet
  server: https://nuget.pkg.github.com/magictrevor/index.json
  username: magictrevor
  api_key:
    secure: o0U09lH4aNaLu0yBHIpwKF1caCqBX6v612buVrfJ3ZQKDCMSfcve9E8HC76v0RG1
  skip_symbols: true
  on:
   branch: master

- provider: NuGet
  name: production
  api_key:
    secure: E7dQMuWgB400XGqZ8X40gI88Tod+1EXnXdQduf1y8VZydrGGcrIFAROGg7XZEgSe
  on:
    branch: master
    appveyor_repo_tag: true
