version: {build}

image: Visual Studio 2019 Preview

pull_requests:
  # Do not increment build number for pull requests
  do_not_increment_build_number: true

nuget:
  # Do not publish NuGet packages for pull requests
  disable_publish_on_pr: true

environment:
  # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

nuget:
  disable_publish_on_pr: true

before_build:
- cmd: dotnet restore

build:
  project: Harmony.sln
  publish_nuget: true
  verbosity: minimal

deploy:
- provider: NuGet
  server: https://nuget.pkg.github.com/magictrevor/index.json
  api_key:
    secure: syppHfiZh7NMERPz6vx5mvN4VgfJPHNtRqiESPtr1Ahg517zHlq7R8mJE8SWpLU7d1LFMb1LfRX3lLZqxue7b3oOHkTnhVfCJk7u5glOfvk=
  username:
    secure: LiBRQO0sP85WoCgDlUaKVw==
  skip_symbols: true
  on:
    branch: master
